"""initial schema

Revision ID: 38d9e7c08224
Revises:
Create Date: 2026-04-07 14:30:01.413554

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38d9e7c08224"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PLATFORM_ROWS = [
    {
        "id": "00000000-0000-0000-0000-000000000001",
        "slug": "instagram",
        "display_name": "Instagram",
        "is_active": True,
        "supports_dm": True,
        "supports_stories": True,
        "supports_reels": True,
        "supports_video": True,
        "supports_polls": False,
    },
    {
        "id": "00000000-0000-0000-0000-000000000002",
        "slug": "tiktok",
        "display_name": "TikTok",
        "is_active": True,
        "supports_dm": True,
        "supports_stories": False,
        "supports_reels": False,
        "supports_video": True,
        "supports_polls": False,
    },
    {
        "id": "00000000-0000-0000-0000-000000000003",
        "slug": "reddit",
        "display_name": "Reddit",
        "is_active": True,
        "supports_dm": True,
        "supports_stories": False,
        "supports_reels": False,
        "supports_video": False,
        "supports_polls": True,
    },
    {
        "id": "00000000-0000-0000-0000-000000000004",
        "slug": "youtube",
        "display_name": "YouTube",
        "is_active": True,
        "supports_dm": False,
        "supports_stories": False,
        "supports_reels": False,
        "supports_video": True,
        "supports_polls": True,
    },
    {
        "id": "00000000-0000-0000-0000-000000000005",
        "slug": "facebook",
        "display_name": "Facebook",
        "is_active": True,
        "supports_dm": True,
        "supports_stories": True,
        "supports_reels": False,
        "supports_video": True,
        "supports_polls": True,
    },
    {
        "id": "00000000-0000-0000-0000-000000000006",
        "slug": "twitter",
        "display_name": "Twitter",
        "is_active": True,
        "supports_dm": True,
        "supports_stories": False,
        "supports_reels": False,
        "supports_video": True,
        "supports_polls": True,
    },
    {
        "id": "00000000-0000-0000-0000-000000000007",
        "slug": "threads",
        "display_name": "Threads",
        "is_active": True,
        "supports_dm": True,
        "supports_stories": False,
        "supports_reels": False,
        "supports_video": True,
        "supports_polls": True,
    },
    {
        "id": "00000000-0000-0000-0000-000000000008",
        "slug": "linkedin",
        "display_name": "LinkedIn",
        "is_active": True,
        "supports_dm": True,
        "supports_stories": False,
        "supports_reels": False,
        "supports_video": True,
        "supports_polls": True,
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("event", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=256), nullable=True),
        sa.Column("account_id", sa.String(length=256), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("cron_expression", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("media_type", sa.String(length=16), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("storage_bucket", sa.String(length=256), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=64), nullable=True),
        sa.Column("generated_by", sa.String(length=64), nullable=True),
        sa.Column("generation_prompt", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personas",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("system_prompt", sa.String(length=4096), nullable=False),
        sa.Column("tone", sa.String(length=64), nullable=False),
        sa.Column("niche", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("vocab_level", sa.String(length=32), nullable=False),
        sa.Column("emoji_usage", sa.String(length=16), nullable=False),
        sa.Column("hashtag_strategy", sa.String(length=32), nullable=False),
        sa.Column("reply_probability", sa.Float(), nullable=False),
        sa.Column("like_probability", sa.Float(), nullable=False),
        sa.Column("follow_back_probability", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "platforms",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("supports_dm", sa.Boolean(), nullable=False),
        sa.Column("supports_stories", sa.Boolean(), nullable=False),
        sa.Column("supports_reels", sa.Boolean(), nullable=False),
        sa.Column("supports_video", sa.Boolean(), nullable=False),
        sa.Column("supports_polls", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    platform_table = sa.table(
        "platforms",
        sa.column("id", sa.UUID(as_uuid=False)),
        sa.column("slug", sa.String(length=32)),
        sa.column("display_name", sa.String(length=64)),
        sa.column("is_active", sa.Boolean()),
        sa.column("supports_dm", sa.Boolean()),
        sa.column("supports_stories", sa.Boolean()),
        sa.column("supports_reels", sa.Boolean()),
        sa.column("supports_video", sa.Boolean()),
        sa.column("supports_polls", sa.Boolean()),
    )
    op.bulk_insert(platform_table, PLATFORM_ROWS)
    op.create_table(
        "proxies",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("protocol", sa.String(length=16), nullable=False),
        sa.Column("host", sa.String(length=256), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("password_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("is_healthy", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.String(length=8), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("hashed_password", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("platform_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("persona_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("credentials_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("platform_user_id", sa.String(length=256), nullable=True),
        sa.Column("platform_metadata", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("suspension_reason", sa.Text(), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("daily_action_limit", sa.Integer(), nullable=False),
        sa.Column("warmup_phase", sa.Boolean(), nullable=False),
        sa.Column("warmup_day", sa.Integer(), nullable=False),
        sa.Column("proxy_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_id"],
            ["proxies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "account_sessions",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("account_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("cookies", sa.JSON(), nullable=True),
        sa.Column("local_storage", sa.JSON(), nullable=True),
        sa.Column("session_storage", sa.JSON(), nullable=True),
        sa.Column("api_tokens_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_reason", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaign_accounts",
        sa.Column("campaign_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("account_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("campaign_id", "account_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("account_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("campaign_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_records",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("task_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("account_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("platform_post_id", sa.String(length=256), nullable=False),
        sa.Column("platform_url", sa.String(length=512), nullable=True),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column("shares_count", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("engagement_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_logs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("task_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_media",
        sa.Column("task_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("media_asset_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "media_asset_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_media")
    op.drop_table("task_logs")
    op.drop_table("post_records")
    op.drop_table("tasks")
    op.drop_table("campaign_accounts")
    op.drop_table("account_sessions")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("proxies")
    op.drop_table("platforms")
    op.drop_table("personas")
    op.drop_table("media_assets")
    op.drop_table("campaigns")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
